### ISSUE TITLE
Resumos e seminários

### ISSUE THREAD

**Issue by iagoac** [iagoac/dce747#1]
# Resumos

Resumos deverão conter entre 250 e 300 palavras e, literalmente, resumir as ideias principais apresentadas em cada texto. Estes não deverão apresentar suas opiniões sobre o tema, limitando-se unicamente a apresentar as ideias que os autores expressaram.

# Seminários

Os seminários deverão ser apresentações curtas (entre 10 e 20 minutos) gravadas em vídeo. O grupo é responsável pela gravação do vídeo e sua divulgação para a turma em algum serviço de *streaming* (Youtube, por exemplo).

O link do seminário deverá ser enviado para meu e-mail (iago.carvalho@unifal-mg.edu.br) até as 23h59 do dia da aula.

Lembrando novamente, o grupo que fizer o seminário não precisa entregar o resumo do texto apresentado.

---

Como não temos um tempo muito grande para dividir todos em grupos, eu tomei a liberdade de fazer isto por mim mesmo! Para isto, eu adicionei todos os alunos em uma lista e embaralhei a ordem dos nomes. Logo após, agrupei os nomes próximos para montar os grupos de forma automática. Este mesmo embaralhamento foi utilizado para definir as datas de cada um dos grupos.

Para isto, eu usei o seguinte código em R:

    alunos <- c("Alice Batista Nogueira","Augusto Georges Adao Miotti","Betania Lopes Silva Marques","Bruna Pereira Falcucci","Caio Marinello Moura Leite","Carlos Eduardo Pavão Aureliano","Douglas Felipe de Morais","Eduardo Guerreiro Rocha","Eduardo Sapio Saccardo","Felipe Martins Choi","Gabriel Takahiro Toma de Lima","Gustavo Celestino de Lima","Gustavo Moreira Penna","Hugo José Teodoro Terra","Iago Vinicius Siqueira Ribeiro","Isabelle Sgrignero","Jasmine Germano França","Jean Vitor da Silva","João Pedro Silva Bianco","Joao Vitor Azevedo Vigarani","Jose Argemiro dos Reis Neto","Leonardo Pessoa Oliveira Alves","Luana de Jesus Carvalho","Lucas Bertoni Scarton","Lucas da Silva Justino","Lucas Dogo de Souza Pezzuto","Lúcio de Moura Peloso","Marcus Vinicius Garcia Miguel","Maria Eduarda Santos Silva","Matheus Malvao Barbosa","Murilo Sousa Moraes","Natália Machado dos Santos","Otávio Augusto Marcelino Izidoro","Paulo Emilio Godinho da Fonseca","Pedro Bortolin","Renê Augusto de Souza","Rodrigo Silva de Paulo","Victor Hugo Tozzo Filho","Victor Ribeiro Gonçalez","Vitor Reis Rubatino","Vitor Risso Parisi")
    set.seed(1)
    sample(alunos)

O resultado deste sorteio encontra-se abaixo

---

**Seminário 1 (aula 06)**
Bruna Pereira Falcucci
Victor Ribeiro Gonçalez
Alice Batista Nogueira
Paulo Emilio Godinho da Fonseca
Luana de Jesus Carvalho

---

**Seminário 2 (aula 08)**
Hugo José Teodoro Terra
Jean Vitor da Silva
Otávio Augusto Marcelino Izidoro
Jose Argemiro dos Reis Neto

---

 **Seminário 3 (aula 10)**
Victor Hugo Tozzo Filho
Felipe Martins Choi
Leonardo Pessoa Oliveira Alves
Renê Augusto de Souza

---  

**Seminário 4 (aula 12)**
Murilo Sousa Moraes
Douglas Felipe de Morais
Eduardo Sapio Saccardo
Iago Vinicius Siqueira Ribeiro

---

**Seminário 5 (aula 16)**
Natália Machado dos Santos
Caio Marinello Moura Leite
Lucas Dogo de Souza Pezzuto
Maria Eduarda Santos Silva

 ---

**Seminário 6 (aula 18)**
Rodrigo Silva de Paulo
Joao Vitor Azevedo Vigarani
Augusto Georges Adao Miotti
Marcus Vinicius Garcia Miguel

---

**Seminário 7 (aula 20)**
Lucas Bertoni Scarton
Matheus Malvao Barbosa
Gustavo Celestino de Lima
Vitor Reis Rubatino

---

**Seminário 8 (aula 23)**
Vitor Risso Parisi
Betania Lopes Silva Marques
Carlos Eduardo Pavão Aureliano
Jasmine Germano França

---

**Seminário 9 (aula 25)**
Lúcio de Moura Peloso
Isabelle Sgrignero
Eduardo Guerreiro Rocha
Lucas da Silva Justino

---

**Seminário 10 (aula 27)**
Pedro Bortolin
Gustavo Moreira Penna
Gabriel Takahiro Toma de Lima
João Pedro Silva Bianco

**Comment by LuScarton** [comment]
Olá Iago! Boa tarde! Tentei entrar em contato contigo via email hoje mais cedo, e não obtive resposta. Acredito que a melhor forma seja através dos Issues aqui mesmo! Em relação aos grupos, como eu faço para trocar de grupo, visto que eu já tinha um grupo pré-formado com algumas pessoas?

**Comment by iagoac** [comment]
@Herooo70 acredito que seja difícil você conseguir o seu grupo completo. A ideia é que vocês troquem de grupo em pares (pessoa A troca de grupo com pessoa B).

Como eu disse, é complicado organizar isto, mas não impossível.

**Comment by AugustoGAMiotti** [comment]
Boa tarde professor, eu entendo a intenção de montar os grupos baseado em um método aleatório, entretanto eu acredito que não leve muito tempo para nós fazermos isso por conta própria, acho que se você estipulasse uma data de por exemplo até amanhã ou no máximo sábado no almoço estaria feito. Fora o fato de como o Lucas (Herooo70) disse, alguns daqui já planejavam fazer os trabalhos no mesmo grupo, já que estudam juntos a algum tempo. Seria possível fazer desse modo, com um membro do grupo mandando os nomes pro seu e-mail no sexta até às 23h ou sábado até às 12h?

**Comment by iagoac** [comment]
@AugustoGAMiotti a ideia aqui é justamente tira-los de sua zona de conforto para que aprendam a trabalhar com pessoas (e situações) diferentes. Isto é uma boa habilidade que vocês deverão desenvolver durante suas carreiras, seja no setor público ou privado. Ainda assim, eu deixei aberto a trocas caso exista alguma incompatibilidade dentro de um mesmo grupo.

O seminário é relativamente pequeno e acredito que vocês consigam fazer funcionar desta maneira.

**Comment by LuScarton** [comment]
Boa tarde Professor! Tentamos fazer essas trocas de pessoas do grupo A pro grupo B, e realmente, é praticamente impossível montarmos o grupo com as pessoas que queríamos inicialmente, mas acredito que todos chegamos em um consenso e a distribuição ficou dessa forma:

**Seminário 1 (aula 06)**
Augusto Georges Adao Miotti
Carlos Eduardo Pavão Aureliano
Lúcio de Moura Peloso
Natália Machado dos Santos
Pedro Bortolin

**Seminário 2 (aula 08)**
Gustavo Celestino de Lima
Vitor Risso Parisi
Iago Vinicius Siqueira Ribeiro
Jose Argemiro dos Reis Neto

**Seminário 3 (aula 10)**
Lucas Bertoni Scarton
Gustavo Moreira Pena
Leonardo Pessoa Oliveira Alves
Jean Vitor da Silva

**Seminário 4 (aula 12)**
Murilo Sousa Moraes
Bruna Pereira Falcucci
Renê Augusto De Souza
Gabriel Takahiro Toma de Lima

**Seminário 5 (aula 16)**
Otávio Augusto Marcelino Izidoro
Hugo José Teodoro Terra
Marcus Vinicius Garcia Miguel
Maria Eduarda Santos Silva

**Seminário 6 (aula 18)**
Lucas Dogo de Souza Pezzuto
João Vitor Azevedo Vigarani
Matheus Malvao Barbosa
Betânia Lopes Silva Marques

**Seminário 7 (aula 20)**
Caio Marinello Moura Leite
Victor Hugo Tozzo Filho
Eduardo Sapio Saccardo
Vitor Reis Rubatino

**Seminário 8 (aula 23)**
Isabelle Sgrignero
Paulo Emilio Godinho da Fonseca
Eduardo Guerreiro Rocha
Jasmine Germano França

**Seminário 9 (aula 25)**
Felipe Martins Choi
Rodrigo Silva de Paulo
Alice Batista Nogueira
Lucas da Silva Justino

**Seminário 10 (aula 27)**
Victor Ribeiro Gonçalez 
Luana de Jesus Carvalho
Douglas Felipe de Morais
João Pedro Silva Bianco

**Comment by iagoac** [comment]
Esta divisão de grupos realmente é de comum consenso de todos os alunos?  
Caso positivo, vocês podem mante-la sem nenhum problema

**Comment by LuScarton** [comment]
Olá Iago! É de comum consenso essa divisão sim!

**Comment by caiomarinello** [comment]
Os resumos precisam ser em inglês?

**Comment by iagoac** [comment]
@caiomarinello de maneira alguma!  
O foco desta disciplina não é em escrita.

Aconselho que todos façam o resumo em Português mesmo

**Comment by caiomarinello** [comment]
Tem alguma margem de erro na questão de palavras necessárias? Um dos meus resumos deu 325 palavras.

**Comment by iagoac** [comment]
@caiomarinello vou postar amanhã a maneira como vou pontuar os resumos.  
O número de palavras do resumo será um dos pontos de avaliação. Desta forma, se você passar (pra mais ou pra menos), vai levar algum desconto
