### ISSUE TITLE
Envio do seminário 08

### ISSUE THREAD

**Issue by jnreis03** [iagoac/dce747#3]
@iagoac , fiz o envio ontem da apresentação para o seu e-mail, pois eu e meu grupo havíamos associado erroneamente a data limite do seminário à data do envio do resumo (ambos da aula 08). Se possível, confirmar o recebimento e considerações acerca do trabalho.

**Comment by iagoac** [comment]
@Xumador ta confirmado. Eu é que acabei errando com a data de entrega das atividades no Moodle.  
Para que ninguém fosse prejudicado, eu optei por deixar tudo para o sábado
