### ISSUE TITLE
publicação do conteúdo e canais de comunicação

### ISSUE THREAD

**Issue by ghost** [iagoac/dce747#4]
existe um grupo no whatsapp pra esse curso? todas as aulas estão no repositório github?

**Comment by iagoac** [comment]
@PhiCross5 oficialmente, não existe nenhum grupo.  
Vou atualizar todas as aulas aqui no próprio github ainda amanhã

**Comment by leonardo-pessoa** [comment]
@iagoac Existe a possibilidade de migração da disponibilização do conteúdo para o moodle?
É o meio de comunicação que estamos acostumados a usar, todas as disciplinas estão focadas lá.
Por aqui eu não recebo notificação de quando as aulas são publicadas, mesmo com o "watch" marcado para receber todas notificações e fica meio confuso ter que acessar o conteúdo por aqui.

**Comment by iagoac** [comment]
@PhiCross5, podemos encontrar um meio do caminho?  

Eu gostaria de continuar disponibilizando o conteúdo por aqui. Entretanto, posso criar um aviso no moodle sempre que uma aula for inserida ou uma atividade for lançada.  
Você acha que desta maneira funcionaria?

**Comment by leonardo-pessoa** [comment]
Acho que seria uma boa.
