### ISSUE TITLE
🤡

### ISSUE THREAD

**Issue by leonardo-pessoa** [iagoac/dce747#6]
Olá Iago, boa tarde. Você disse dia 7 de DEZEMBRO do ano passado que iria postar no mínimo uma notificação pra gente no moodle de quando novos conteúdos fossem postados. Sua falta de organização com suas disciplinas está atrapalhando toda a turma, visto que você não atualiza os hyperlinks na página inicial (aulas 08/12 | 15/12 | 22/12 | 23/12 | 03/02 | 09/02). Tenho certeza que essa indignação não é só de minha parte e venho por meio deste issue (já que você insiste em continuar sua disciplina nesta plataforma que não é a oficial da faculdade) para cobrar um posicionamento mais justo de sua parte para conosco. O mínimo aceitável seria que fôssemos avisados com antecedência dos nossos afazeres, em vez de postar HOJE um link no moodle de um resumo que seria pra HOJE mesmo, desde as ultimas aulas. Será que podemos resolver essa situação sem a necessidade de acionar o colegiado do curso? Aguardo respostas.

**Comment by JoaoBianco** [comment]
Concordo, não é justo a falta de organização de uma matéria afetar os alunos desse jeito. Uma atividade que deve ser entregue deveria estar marcada no Moodle com NO MINIMO 3 dias de antecedência para podermos nos organizar e realizar ela de maneira efetiva e bem feita... e como o GitHub não é uma "plataforma oficial" da Unifal para uso no ERE, o aviso deveria ser o mais breve possível visando não prejudicar ninguém.

**Comment by LuScarton** [comment]
Concordo com o Leonardo! Acho que podemos resolver entre a gente, sem a necessidade de acionar o coordenador Eliseu ou até mesmo o colegiado do curso, porém precisamos que algo seja feito a respeito desses problemas, em vez de mais promessas vazias, igual o último Issue onde você disse que iria postar notificação no moodle (como bem lembrou o próprio Leonardo no post acima), e tudo que temos é apenas o link para enviar as atividades (que são postados em cima da hora).

**Comment by gabriel-takahiro** [comment]
Boa tarde, Iago. Gostaria de saber se esta disciplina terá aulas gravadas, pois desde o dia 1 de Dezembro do ano passado não temos essas gravações, apenas um texto em pdf.

**Comment by iagoac** [comment]
Olá a todos,

bem, vamos lá então... O que vocês acham de postergar a entrega de todas as atividades (incluindo a de hoje) para o dia 31/03?

Todos os links serão criados no Moodle e os textos disponibilizados para que vocês possam fazer a entrega quando bem entenderem (incluindo os seminários).

Estou terminando de trabalhar no conteúdo das aulas e também vou soltar os PDFs e os vídeos o mais rápido que eu conseguir.

**Comment by LuScarton** [comment]
Agradecemos pela sua compreensão e acho extremamente válido postergar a entrega, porém gostaria que você entendesse que o problema está na falta de comunicação. Se você postasse as aulas nos dias correspondentes, e nos avisasse sobre as entregas com antecedência, não teríamos que chegar neste ponto que chegamos. Acredito que estes problemas servem para nos abrir os olhos e aprendermos com nossos erros, para que eles não ocorram novamente com as novas disciplinas. Parabéns pela atitude e, mais uma vez, obrigado pela compreensão.

**Comment by iagoac** [comment]
@Herooo70 eu entendo o problema da falha de comunicação. Mais além, eu assumo que este é um problema meu e não de vocês.  Assim, eu peço desculpas pelos fatos ocorridos e vou tentar corrigir da melhor maneira o possível. Estou aberto a discussão caso exista outros pontos que possam ser melhorados.

Estou trabalhando para melhorar isto nesta disciplina e em todas as disciplinas posteriores.

**Comment by iagoac** [comment]
Os textos já estão todos postados.  
Além disso, as atividades para entrega no Moodle também já foram criadas.

Vou avisar agora no Moodle e no Classroom.

Esotu trabalhando no restante do material e espero ter novidades em breve.
