### ISSUE TITLE
Seminário aula 12 

### ISSUE THREAD

**Issue by R50UZ4** [iagoac/dce747#8]
Boa tarde, Iago!
Nós enviamos o link do seminário no dia 16/12 para o seu e-mail. Contudo o link do nosso seminário não se apresenta na página inicial da disciplina no GitHub.
Você poderia confirmar o recebimento do e-mail? Lembrando novamente que o mesmo foi enviado dentro do prazo de entrega e caso não o tenha recebido podemos enviar de novo.

**Comment by iagoac** [comment]
Olá @R50UZ4 eu confirmo o recebimento na data correta.  
Acabei de inserir o seminário na página da disciplina.

Com isto, vou fechar este issue
